version: "3.3"

services:
  grist:
    image: gristlabs/grist-omnibus:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      URL: https://${DOMAIN}
      HTTPS: auto
      TEAM: grist-team
      EMAIL: ${ADMIN_EMAIL}
      PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./storage:/persist
    ports:
      - 172.17.0.1:32531:443
