version: "3.3"

services:
  grist:
    image: gristlabs/grist:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      GRIST_SESSION_SECRET: ${ADMIN_PASSWORD}
    ports:
      - 172.17.0.1:32531:8484
    volumes:
      - ./storage:/persist
